apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: petclinic
  name: petclinic
  namespace: ${NAMESPACE}
spec:
  replicas: ${REPLICAS}
  selector:
    matchLabels:
      app: petclinic
  strategy: {}
  template:
    metadata:
      labels:
        app: petclinic
    spec:
      containers:
      - image: ${K8S_IMAGE}
        imagePullPolicy: Always
        name: petclinic
        ports:
        - containerPort: 8082
          name: http
          protocol: TCP
