name: Test workflows

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - 'feature/*'

jobs:
  build:
    runs-on: ubuntu-latest
    name : Build

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Cache Maven packages
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Build with Maven
      run: mvn clean install

    - name: Run tests
      run: mvn test

    - name: Upload Artifact
      if: success()  # Only execute if previous steps were successful
      uses: actions/upload-artifact@v4
      with:
        name: petclinic-war
        #path: "/home/runner/work/Petclinic/Petclinic/target/petclinic.war"
        path: ./target/petclinic.war
        if-no-files-found: error  # Fail the workflow if no files are found to upload

    - name: Docker Login
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Docker Build for Testing
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true                   # disable push during test build
        tags: ${{ vars.DOCKERHUB_USERNAME }}/petclinic:${{ github.sha }}

  # deploy:
  #   environment: development
  #   runs-on: ubuntu-latest
  #   name : deploy
